paths:
  panel: panel

  secret: secret

  public: public

  public_assets: assets

  dev:
    views: src/pug-views
    js: src/js-modules
    css: src/scss

  https: # путь к частям HTTPS-сертификата
    key: ssl/https.key
    cert: ssl/https.cert
    ca: ''

  api: api-sources

users:
  test:
    isAdmin: true
    userName: 'Test testowich'

api_endpoints:
  vk: https://api.vk.com/method
  vk_ac: https://oauth.vk.com/access_token
  vk_au: https://oauth.vk.com/authorize

vk_data:
  comID: 0         # ID сообщества, из которого будет браться информация
  appID: 0         # ID связанного приложения (vk.com/apps?act=manage)
  api_version: 0   # версия VK API
  secret: ''       # защищённый ключ из связанного приложения
  service: ''      # сервисный ключ доступа из связанного приложения

vendors:
  js:

    # cdnjs.com/libraries/moment.js (moment.min.js & ru.js)
    # cdnjs.com/libraries/moment-timezone (moment-timezone-with-data.min.js)
    moment:
        v:
          same: 2.22.2
          timezone: 0.5.23
        sri:
          same: sha256-CutOzxCRucUsn6C6TcEYsauvvYilEniTXldPa6/wu0k=
          locale: sha256-qR4pdhxtx7dwKGJuYGoYjfnCQBPXv47hzLLU8jPLVUY=
          timezone: sha256-15jnh2lee6Li94j6XCbw8PRzNZe29O/W9i97yXVyRmA=
